Models/ErrorViewModel.cs
using System;

namespace ArmyTechTask.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/BranchController.cs
using ArmyTechTask.Services;
using ArmyTechTask.viewModels.Branch;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ArmyTechTask.Controllers
{
    [Route("[controller]")]
    public class BranchController : Controller
    {
        private IBranchService branchService;

        public BranchController(IBranchService branchService)
        {
            this.branchService = branchService;
        } 

        [HttpGet]
        [Route("GetAllBranches")]
        public List<BranchVM> GetAllBranches()
        {
            return branchService.GetAll();
        }
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/CacherController.cs
using ArmyTechTask.Services;
using ArmyTechTask.viewModels.Branch;
using ArmyTechTask.viewModels.Cacher;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ArmyTechTask.Controllers
{
    [Route("[controller]")]
    public class CacherController : Controller
    {
        private ICacherService cacherService; 

        public CacherController(ICacherService cacherService )
        {
            this.cacherService = cacherService; 
        }
        [HttpGet] 
        [Route("Get/{id}")]
        public CacherDetailsVM Get(int id)
        {
            return cacherService.GetCacherById(id); 
        }
        [HttpGet]
        public IActionResult Index()
        {
            //TempData.Keep("message");
            //TempData.Keep("type");
            var x = TempData;
            var result = cacherService.GetAll();
            ViewBag.CachierList = result;
            return View();
        }
        [HttpPost]
        [Route("AddCacher")]
        public IActionResult AddCacher(CacherAddVM entity)
        {
            if (ModelState.IsValid)
            {
                var result = cacherService.AddCacher(entity);
                if (result.Success)
                {
                    TempData["success"] = "Successfully Added Cashier"; 
                }
                else
                {
                    TempData["error"] = "Failed to Add Cashier"; 
                }
            }
            else
            {
                TempData["error"] = "Form Not Correct "; 
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        [Route("UpdateCacher")]
        public IActionResult UpdateCacher(CacherAddVM entity)
        {
            if (ModelState.IsValid)
            {
               var result= cacherService.UpdateCacher(entity);
                if (result.Success)
                { 
                    TempData["success"] = "Successfully Update Cashier"; 
                }
                else
                {
                    TempData["error"] = "Failed to Update Cashier"; 
                } 
            }
            else
            {
                TempData["error"] = "Form Not Correct "; 
            }
            return RedirectToAction("Index");
        } 

        [Route("deleteCacher")]
        public IActionResult deleteCacher(int id)
        {
            var result = cacherService.DeleteCacher(id);
            if (result.Success)
            {
                TempData["success"] = "Successfully delete Cashier"; 
            }
            else
            {
                TempData["error"] = "Failed to delete Cashier"; 
            }
            return RedirectToAction("Index");
        } 
    }
}

Controllers/HomeController.cs
using ArmyTechTask.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ArmyTechTask.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/invoiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace ArmyTechTask.Controllers
{
    public class invoiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
    //PM> Scaffold-DbContext "Server=.;Database=ArmyTechTask;Trusted_Connection=True;" Microsoft.EntityFrameworkCore.SqlServer -OutputDir Domains

}

Views/Cacher/Index.cshtml
@model ArmyTechTask.viewModels.Cacher.CacherVM;
@{
    ViewData["Title"] = "Home page";
    ///ViewBag.CachierList
}
  @if (TempData["success"] != null )
            {
                <script type="text/javascript"> 
                    window.onload = function () {  swal("Good job!", '@TempData["success"]', "success");  }; 
                </script>
            }else if(TempData["error"] != null){ <script type="text/javascript"> swal("Good job!", '@TempData["error"]', "error"); </script> }
<div class="page-header d-md-flex justify-content-between">
    <div>
        <h3>Cacher</h3> 
    </div>
    <div class="mt-2 mt-md-0">
        <a href="#" class="btn btn-success AddNewItem" data-toggle="modal" data-target="#mdlNew" title="Add new item">Add new item</a>
    </div>
</div>

<div class="row">
    <div class="col-md-12">

        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="user-list" class="table table-lg">
                        <thead>
                            <tr class="align-content-center">
                                <th class="align-align-content-center">ID</th>
                                <th>Casher Name</th>
                                <th>Branch Name</th> 
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{int i = 1;}
                             @{
                                    foreach (var item in @ViewBag.CachierList)
                                    {
                                        <tr>
                                          <td>@(i++)</td>
                                           <td>@item.CashierName</td>
                                           <td>@item.BranchName</td>
                                           <td>
                                            <input type="hidden" class="id" value="@item.Id" />
                                            <a href="#editModal" class="edit align-content-center btn-primary p-2 m-1" data-toggle="modal">
                                            <i class="material-icons col-md-5" data-toggle="tooltip" title="Edit">&#xE254;</i>
                                             edit
                                            </a> 
                                           <a class="align-content-center btn-danger p-2 m-1"  asp-controller="Cacher" asp-action="deleteCacher" asp-route-id="@item.Id">delete</a>
                                           </td> 
                                        </tr>
                                    }
                                } 
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div id="mdlNew" class="modal fade modal-item" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title">Add new Casher</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="ti-close"></i>
                </button>
            </div>
            <div id="frmItem"> 
                <form method="post" asp-controller="Cacher" asp-action="AddCacher"> 
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Cashier Name</label>
                                    <input type="text" class="form-control" name="CashierName" />
                                </div>
                                <div class="form-group">
                                    <label >Branch</label>
                                   <select name="BranchId" id="BranchId" class="form-control addBranchselectList"> </select> 
                              </div>
                            </div>
                        </div> 
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            Close
                        </button>
                        <button type="submit" name="btnSave" id="btnsubmit" class="btn btn-primary" title="Save">Save</button>
                    </div>
                </form>
                @*</form> *@
            </div>
        </div>
    </div>
</div>
<div id="editModal" class="modal fade modal-item" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title">update Casher</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i class="ti-close"></i>
                </button>
            </div>
            <div > 
                <form method="post" asp-controller="Cacher" asp-action="UpdateCacher">
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label>Cashier Name</label>
                                    <input type="hidden" class="id" name="id" />
                                    <input type="text" class="form-control" name="CashierName" />
                                </div>
                                <div class="form-group">
                                    <label >Branch</label>
                                   <select name="BranchId" id="BranchId" class="form-control updateBranchselectList"> 
                                   </select> 
                              </div>
                            </div>
                        </div> 
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">
                            Close
                        </button>
                        <button type="submit" name="btnSave" id="btnsubmit" class="btn btn-primary" title="Save">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script type="text/javascript">

        //  click edit button
         $('table .edit').on('click', function () {
             debugger
             GetAllBranches("update");
                    var id = $(this).parent().find('.id').val();
                    $.ajax({
                        type: 'GET',
                        url: '/Cacher/Get/'+id,
                        success: function (CacherData) { 
                            $('#editModal input[name="id"]').val(CacherData.id);
                            $('#editModal input[name="CashierName"]').val(CacherData.cashierName);
                            $('.updateBranchselectList')[0].val(CacherData.branchId);
                            ///branchId branchName

                        }
                    })  
            }); 
         $('.AddNewItem').on('click',function(){
              GetAllBranches("add");
          })
            function GetAllBranches(type){  
                debugger
                var selectList =(type=="add")? document.getElementsByClassName("addBranchselectList")[0]:document.getElementsByClassName("updateBranchselectList")[0]; 
                 $.ajax({
                        type: 'GET',
                        url: '/Branch/GetAllBranches',
                        success: function (BranchesData) {
                            debugger
                              //Create and append the options
                            for (var i = 0; i < BranchesData.length; i++) {
                                var option = document.createElement("option");
                                option.value = BranchesData[i].id;
                                option.text = BranchesData[i].branchName;
                                selectList.appendChild(option);
                            }
                        }
                    })  
            } 
    </script>
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArmyTechTask</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" /> 
    @*for sweetalert*@
    <link media="screen" rel="stylesheet" href="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.css" />
    <link media="screen" rel="stylesheet" href='https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.css' />
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bluebird/3.3.5/bluebird.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script type="text/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script type="text/javascript" src="https://cdn.jsdelivr.net/sweetalert2/6.3.8/sweetalert2.min.js"></script>


</head>
<body>
    <header>
       
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ArmyTechTask</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @*<ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>*@
                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
             <nav aria-label="breadcrumb" class="d-flex align-items-start">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item">
                                <a asp-action="index" asp-controller="Cacher">Cacher Management</a>
                            </li>
                             <li class="breadcrumb-item">
                                <a asp-action="index" asp-controller="Invoice">Invoice Management</a>
                            </li>
                        </ol>
                    </nav>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ArmyTechTask - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script> 
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>